# Generated by Django 4.2.14 on 2024-08-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('su_auth', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
