# Generated by Django 5.0.7 on 2024-12-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_auth', '0004_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loginProvider',
        ),
        migrations.AddField(
            model_name='user',
            name='is_authenticated_with_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_authenticated_with_google',
            field=models.BooleanField(default=False),
        ),
    ]
