# Generated by Django 5.0.7 on 2024-12-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_auth', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
